// src/lib/components/print/InlineHighlights.svelte
<script lang="ts">
	let { text, highlights = [] }: { text: string; highlights?: string[] } = $props();

	const escapedHighlights = $derived(
		highlights.map((highlight) => highlight.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
	);
	const parts = $derived(
		escapedHighlights.length > 0
			? text.split(new RegExp(`(${escapedHighlights.join('|')})`, 'g'))
			: [text]
	);
</script>

{#each parts as part, index (`${part}-${index}`)}
	{#if highlights.includes(part)}
		<strong class="document-emphasis">{part}</strong>
	{:else}
		{part}
	{/if}
{/each}

// src/components/print/inline-highlights.tsx
const REGEX_SPECIAL = /[.*+?^${}()|[\]\\]/g;

export function InlineHighlights({
	text,
	highlights = []
}: {
	text: string;
	highlights?: string[];
}) {
	if (highlights.length === 0) return <>{text}</>;

	const escaped = highlights.map((highlight) => highlight.replace(REGEX_SPECIAL, '\\$&'));
	const parts = text.split(new RegExp(`(${escaped.join('|')})`, 'g'));

	return (
		<>
			{parts.map((part, index) =>
				highlights.includes(part) ? (
					<strong className="document-emphasis" key={`${part}-${index}`}>
						{part}
					</strong>
				) : (
					part
				)
			)}
		</>
	);
}
